### PR TITLE
Use libprotobuf 3.5

### PR DESCRIPTION
**Pull request by jakirkham**
Now that we have `libprotobuf` in conda-forge, switch over to it. Also switch to the latest version.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thoughts @gokceneraslan?

**Comment by jakirkham** [comment]
Friendly nudge @gokceneraslan. 😉

**Comment by gokceneraslan** [comment]
Oh, sorry. Why do we switch to libprotobuf now?

**Comment by gokceneraslan** [comment]
OK, it's written in the commit. Then I merge this as tests are also fine.

**Comment by jakirkham** [comment]
No worries. It will also be a dependency tracked by `conda-build` 3 when we switch. ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/20 ) So it should avoid the manual work done to pin it here.

**Pull request merged**
